 assignmentDialogHandler(
        allRooms,
        currentDialog,
        currentGroup,
        setIsSubmited,
        setConfirmed,
        assignedRoomsNumbers,
        setCurrentDialog,
        assignmentDicionariesArray,
        setAssignmentDicionariesArray,
        setAssignedRoomsNumbers,
        setCurrentGroup,
        setOpen,
        setAssigned
);
