 assignmentDialogHandler(
        allBoxes,
        currentDialog,
        currentGroup,
        setIsSubmited,
        setConfirmed,
        assignedBoxesNumbers,
        setCurrentDialog,
        assignmentDicionariesArray,
        setAssignmentDicionariesArray,
        setAssignedBoxesNumbers,
        setCurrentGroup,
        setOpen,
        setAssigned
);
